### ISSUE TITLE
Boundary leakages when using regional wind_data

### ISSUE THREAD

**Issue by jcfbeardsley** [weatherlayers/deck.gl-particle#10] opened 2022-09-11 04:06 UTC
Hi @zakjan,

Firstly, great work on developing this repo! Thanks for all your efforts, this is a really cool tool.

In my most recent testing, I noted that you have exposed the `bounds` and `textureParameters` to enable the use of wind data with limited spatial coverage. This works well for the intended area when you swap `GL.REPEAT` for `GL.CLAMP_TO_EDGE`, but I'm seeing some weird 'leakages' beyond the specified bounds (see one large leakage in the north and two smaller leakages in the east of [this demo here](https://codesandbox.io/s/npm-playground-forked-ik52k4?file=/src/index.js)). In this case the wind data is just cropped and upscaled version of the 0.25 deg GFS model for testing. Any ideas what might be going on here and how it could be resolved?

Also for your own reference, I had issues when generating the data PNG using the repo instructions. Omitting the blue channel was generating an image with `gdal_translate` that had alpha transparency which wasn't working in WebGL, but looking at your sample wind data I could see that the blue channel was just set the same as green. To work around this, I changed the `gdalbuildvrt` command to specify the v data to the blue channel as well, i.e.:

`gdalbuildvrt -separate wind_data_world.vrt u.grib v.grib v.grib`

Then the `gdal_translate` function (and WebGL) worked as expected. This may be a change with the latest release of GDAL?

Cheers,
J.

**Comment by jcfbeardsley** [comment] 2022-09-11 07:04
As a follow up, I've discovered this is occurring at edges of the png which have wind data values:

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/63836041/189516181-48dbe4d1-36e0-4fee-82b3-14a84f504165.png">

I've worked around this by adding a 1px no-data buffer to the wind_data.png, but am still at a loss for what's causing the original leakage beyond the defined particle bounds.

**Comment by zakjan** [comment] 2022-09-11 07:23
Thanks for the investigation. I'm glad you found a workaround. It seems that the issue is in missing check to disable rendering outside of `bounds` (it's used for projection only). I'll have a look.

**Comment by zakjan** [comment] 2022-09-12 18:27
I have pushed a fix for the issue and released 1.1.0. You shouldn't need to override `textureParameters` anymore. Could you try it out?

There are more changes in the release, for your demo it's noteworthy that there is a new required param `imageUnscale: [-128, 127]` to pass the original data bounds, and `_animate: true` is not necessary anymore.

**Comment by zakjan** [comment] 2022-10-06 22:13
Closing as completed, feel free to reopen if there are further issues.

**Closed by zakjan** 2022-10-06 22:13 UTC
